version: "3.9"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "14566:4566" # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=dynamodb,lambda,logs # 起動するサービス
      - START_WEB=1 # LocalStackの管理コンソールを無効化
      - DEFAULT_REGION=us-east-1 # デフォルトのリージョン
      - DEBUG=1 # デバッグモードの有効化
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Dockerデーモンへのアクセス
